/**
 * Generated from Tau's curated model catalogue (tau/builtins/models/text/*.py).
 *
 * `input`/`output` are the modalities the model accepts and produces, normalised to a
 * stable order. Input matters operationally: a model without `image` cannot be shown a
 * screenshot, so the observation mode falls back to the text-only tree for it.
 *
 * `thinkingLevels` comes from Tau's per-model research. A model carrying 'off' can have
 * reasoning disabled, which is the difference between a 2-second and an 8-second turn.
 *
 * Regenerate rather than edit by hand.
 */

import type { ModelConfig } from './registry'

export const CATALOGUE: readonly ModelConfig[] = [
  // ---- gemini (7) ---------------------------------------------------
  { provider: "gemini", id: "gemini-3.7-flash", label: "Gemini 3.7 Flash", tools: true, input: ["text", "image", "audio", "video", "file"], output: ["text"], thinkingLevels: ["low", "medium", "high"], thinkingFormat: "gemini", context: 1048576 },
  { provider: "gemini", id: "gemini-3.5-flash", label: "Gemini 3.5 Flash", tools: true, input: ["text", "image", "audio", "video", "file"], output: ["text"], thinkingLevels: ["minimal", "low", "medium", "high"], thinkingFormat: "gemini", context: 1048576 },
  { provider: "gemini", id: "gemini-3.1-flash-lite", label: "Gemini 3.1 Flash Lite", tools: true, input: ["text", "image", "audio", "video", "file"], output: ["text"], thinkingLevels: ["minimal", "low", "medium", "high"], thinkingFormat: "gemini", context: 1048576 },
  { provider: "gemini", id: "gemini-3.1-pro-preview", label: "Gemini 3.1 Pro Preview", tools: true, input: ["text", "image", "audio", "video", "file"], output: ["text"], thinkingLevels: ["low", "medium", "high"], thinkingFormat: "gemini", context: 1048576 },
  { provider: "gemini", id: "gemini-2.5-pro", label: "Gemini 2.5 Pro", tools: true, input: ["text", "image", "audio", "video", "file"], output: ["text"], thinkingLevels: ["minimal", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "gemini", context: 1048576 },
  { provider: "gemini", id: "gemini-2.5-flash", label: "Gemini 2.5 Flash", tools: true, input: ["text", "image", "audio", "video", "file"], output: ["text"], thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"], thinkingFormat: "gemini", context: 1048576 },
  { provider: "gemini", id: "gemini-2.5-flash-lite", label: "Gemini 2.5 Flash Lite", tools: true, input: ["text", "image", "audio", "video", "file"], output: ["text"], thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"], thinkingFormat: "gemini", context: 1048576 },

  // ---- openai (6) ---------------------------------------------------
  { provider: "openai", id: "gpt-5.5", label: "GPT-5.5", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh"], context: 1050000 },
  { provider: "openai", id: "gpt-5.4", label: "GPT-5.4", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh"], context: 1050000 },
  { provider: "openai", id: "gpt-5.4-mini", label: "GPT-5.4 Mini", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh"], context: 400000 },
  { provider: "openai", id: "gpt-5.6-sol", label: "GPT-5.6 Sol", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh", "max"], context: 1050000 },
  { provider: "openai", id: "gpt-5.6-terra", label: "GPT-5.6 Terra", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh", "max"], context: 1050000 },
  { provider: "openai", id: "gpt-5.6-luna", label: "GPT-5.6 Luna", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh", "max"], context: 1050000 },

  // ---- anthropic (7) ------------------------------------------------
  { provider: "anthropic", id: "claude-fable-5", label: "Claude Fable 5", tools: true, input: ["text", "image", "file"], output: ["text"], thinkingLevels: ["low", "medium", "high", "xhigh", "max"], thinkingFormat: "anthropic", context: 1048576 },
  { provider: "anthropic", id: "claude-opus-5", label: "Claude Opus 5", tools: true, input: ["text", "image", "file"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "anthropic", context: 1048576 },
  { provider: "anthropic", id: "claude-opus-4-8", label: "Claude Opus 4.8", tools: true, input: ["text", "image", "file"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "anthropic", context: 1048576 },
  { provider: "anthropic", id: "claude-opus-4-7", label: "Claude Opus 4.7", tools: true, input: ["text", "image", "file"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "anthropic", context: 1048576 },
  { provider: "anthropic", id: "claude-sonnet-5", label: "Claude Sonnet 5", tools: true, input: ["text", "image", "file"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "anthropic", context: 1048576 },
  { provider: "anthropic", id: "claude-sonnet-4-6", label: "Claude Sonnet 4.6", tools: true, input: ["text", "image", "file"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "max"], thinkingFormat: "anthropic", context: 1048576 },
  { provider: "anthropic", id: "claude-haiku-4-5-20251001", label: "Claude Haiku 4.5", tools: true, input: ["text", "image", "file"], output: ["text"], thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "anthropic", context: 200000 },

  // ---- nvidia (15) --------------------------------------------------
  { provider: "nvidia", id: "nvidia/nemotron-3.5-lightning-30b-a3b", label: "Nemotron 3.5 Lightning 30B", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "chat-template", context: 1000000 },
  { provider: "nvidia", id: "meta/muse-glimmer-30b", label: "Muse Glimmer 30B", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["low", "medium", "high", "xhigh"], context: 131072 },
  { provider: "nvidia", id: "poolside/laguna-xs-2.1", label: "Laguna XS 2.1", tools: true, input: ["text"], output: ["text"], context: 262144 },
  { provider: "nvidia", id: "minimaxai/minimax-m3", label: "MiniMax M3", tools: true, input: ["text", "image", "video"], output: ["text"], context: 1000000 },
  { provider: "nvidia", id: "google/diffusiongemma-26b-a4b-it", label: "DiffusionGemma 26B A4B IT", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "chat-template", context: 262144 },
  { provider: "nvidia", id: "nvidia/nemotron-3-ultra-550b-a55b", label: "Nemotron 3 Ultra 550B", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "medium", "high"], context: 1000000 },
  { provider: "nvidia", id: "stepfun-ai/step-3.7-flash", label: "Step 3.7 Flash", tools: true, input: ["text", "image"], output: ["text"], context: 256000 },
  { provider: "nvidia", id: "openai/gpt-oss-120b", label: "GPT-OSS 120B", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["low", "medium", "high"], context: 128000 },
  { provider: "nvidia", id: "openai/gpt-oss-20b", label: "GPT-OSS 20B", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["low", "medium", "high"], context: 128000 },
  { provider: "nvidia", id: "deepseek-ai/deepseek-v4-pro-0813", label: "DeepSeek V4 Pro", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high", "max"], context: 1000000 },
  { provider: "nvidia", id: "deepseek-ai/deepseek-v4-flash-0731", label: "DeepSeek V4 Flash", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high", "max"], context: 1000000 },
  { provider: "nvidia", id: "google/gemma-4-31b-it", label: "Gemma 4 31B IT", tools: true, input: ["text", "image", "video"], output: ["text"], context: 131072 },
  { provider: "nvidia", id: "moonshotai/kimi-k2.6", label: "Kimi K2.6", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "deepseek", context: 131072 },
  { provider: "nvidia", id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning", label: "Nemotron 3 Nano Omni", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["off", "high"], context: 131072 },
  { provider: "nvidia", id: "nvidia/nemotron-3-super-120b-a12b", label: "Nemotron 3 Super 120B", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "medium", "high"], context: 262144 },

  // ---- openrouter (249) ----------------------------------------------
  { provider: "openrouter", id: "dots-studio/dots-3-note-preview:free", label: "Dots Studio: Dots3-Note Preview (free)", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 512000 },
  { provider: "openrouter", id: "google/gemini-3.7-flash", label: "Google: Gemini 3.7 Flash", tools: true, input: ["text", "image", "audio", "video"], output: ["text"], thinkingLevels: ["low", "medium", "high"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "bytedance-seed/seed-2-1-turbo", label: "ByteDance Seed: Seed 2.1 Turbo", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "qwen/qwen3.8-2.4t-a95b", label: "Qwen: Qwen3.8 2.4T A95B", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["low", "medium", "xhigh"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "bytedance-seed/seed-2.0-code", label: "ByteDance Seed: Seed-2.0-Code", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "deepseek/deepseek-v4-pro-0813", label: "DeepSeek: DeepSeek V4 Pro 0813", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "low", "high", "max"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "nvidia/nemotron-3.5-lightning", label: "NVIDIA: Nemotron 3.5 Lightning", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "nvidia/nemotron-3.5-lightning:free", label: "NVIDIA: Nemotron 3.5 Lightning (free)", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "upstage/solar-pro4", label: "Upstage: Solar Pro 4", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 524288 },
  { provider: "openrouter", id: "meta/muse-glimmer-30b", label: "Meta: Muse Glimmer 30B", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "meta/muse-spark-1.2", label: "Meta: Muse Spark 1.2", tools: true, input: ["text", "image", "audio", "video"], output: ["text"], thinkingLevels: ["minimal", "low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "qwen/qwen3.8-max", label: "Qwen: Qwen3.8 Max", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["minimal", "low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "deepseek/deepseek-v4-flash-0731", label: "DeepSeek: DeepSeek V4 Flash 0731", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "low", "high", "max"], thinkingFormat: "openrouter", context: 1310720 },
  { provider: "openrouter", id: "thinkingmachines/inkling-small", label: "Thinking Machines: Inkling Small", tools: true, input: ["text", "image", "audio"], output: ["text"], thinkingLevels: ["off", "minimal", "low", "medium", "high", "max"], thinkingFormat: "openrouter", context: 524288 },
  { provider: "openrouter", id: "anthropic/claude-opus-5-fast", label: "Claude Opus 5 (Fast)", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "anthropic/claude-opus-5", label: "Claude Opus 5", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "google/gemini-3.6-flash", label: "Google: Gemini 3.6 Flash", tools: true, input: ["text", "image", "audio", "video"], output: ["text"], thinkingLevels: ["minimal", "low", "medium", "high"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "thinkingmachines/inkling", label: "Thinking Machines: Inkling", tools: true, input: ["text", "image", "audio"], output: ["text"], thinkingLevels: ["off", "minimal", "low", "medium", "high", "max"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "moonshotai/kimi-k3", label: "MoonshotAI: Kimi K3", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["off", "low", "high", "max"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "openai/gpt-5.6-luna-pro", label: "OpenAI: GPT-5.6 Luna Pro", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 1050000 },
  { provider: "openrouter", id: "openai/gpt-5.6-luna", label: "OpenAI: GPT-5.6 Luna", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 1050000 },
  { provider: "openrouter", id: "openai/gpt-5.6-terra-pro", label: "OpenAI: GPT-5.6 Terra Pro", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 1050000 },
  { provider: "openrouter", id: "openai/gpt-5.6-terra", label: "OpenAI: GPT-5.6 Terra", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 1050000 },
  { provider: "openrouter", id: "openai/gpt-5.6-sol-pro", label: "OpenAI: GPT-5.6 Sol Pro", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 1050000 },
  { provider: "openrouter", id: "openai/gpt-5.6-sol", label: "OpenAI: GPT-5.6 Sol", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 1050000 },
  { provider: "openrouter", id: "x-ai/grok-4.6", label: "xAI: Grok 4.6", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 500000 },
  { provider: "openrouter", id: "qwen/qwen3.8-27b", label: "Qwen: Qwen3.8 27B", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "qwen/qwen3.7-max", label: "Qwen: Qwen3.7 Max", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "x-ai/grok-build-0.1", label: "xAI: Grok Build 0.1", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["low", "medium", "high"], thinkingFormat: "openrouter", context: 256000 },
  { provider: "openrouter", id: "google/gemini-3.5-flash", label: "Google: Gemini 3.5 Flash", tools: true, input: ["text", "image", "audio", "video"], output: ["text"], thinkingLevels: ["minimal", "low", "medium", "high"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "anthropic/claude-opus-4.7-fast", label: "Anthropic: Claude Opus 4.7 (Fast)", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "inclusionai/ring-2.6-1t", label: "inclusionAI: Ring-2.6-1T", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["minimal", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "google/gemini-3.1-flash-lite", label: "Google: Gemini 3.1 Flash Lite", tools: true, input: ["text", "image", "audio", "video"], output: ["text"], thinkingLevels: ["minimal", "low", "medium", "high"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "openai/gpt-chat-latest", label: "OpenAI: GPT Chat Latest", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 400000 },
  { provider: "openrouter", id: "x-ai/grok-4.3", label: "xAI: Grok 4.3", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "ibm-granite/granite-4.1-8b", label: "IBM: Granite 4.1 8B", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "mistralai/mistral-medium-3-5", label: "Mistral: Mistral Medium 3.5", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free", label: "NVIDIA: Nemotron 3 Nano Omni (free)", tools: true, input: ["text", "image", "audio", "video"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 256000 },
  { provider: "openrouter", id: "~anthropic/claude-haiku-latest", label: "Anthropic Claude Haiku Latest", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 200000 },
  { provider: "openrouter", id: "~openai/gpt-mini-latest", label: "OpenAI GPT Mini Latest", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 400000 },
  { provider: "openrouter", id: "~google/gemini-pro-latest", label: "Google Gemini Pro Latest", tools: true, input: ["text", "image", "audio", "video"], output: ["text"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "~moonshotai/kimi-latest", label: "MoonshotAI Kimi Latest", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 262142 },
  { provider: "openrouter", id: "~google/gemini-flash-latest", label: "Google Gemini Flash Latest", tools: true, input: ["text", "image", "audio", "video"], output: ["text"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "~anthropic/claude-sonnet-latest", label: "Anthropic Claude Sonnet Latest", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "~openai/gpt-latest", label: "OpenAI GPT Latest", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 1050000 },
  { provider: "openrouter", id: "qwen/qwen3.5-plus-20260420", label: "Qwen: Qwen3.5 Plus 2026-04-20", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "qwen/qwen3.6-flash", label: "Qwen: Qwen3.6 Flash", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "qwen/qwen3.6-35b-a3b", label: "Qwen: Qwen3.6 35B A3B", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "qwen/qwen3.6-max-preview", label: "Qwen: Qwen3.6 Max Preview", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "qwen/qwen3.6-27b", label: "Qwen: Qwen3.6 27B", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 262140 },
  { provider: "openrouter", id: "openai/gpt-5.5-pro", label: "OpenAI: GPT-5.5 Pro", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 1050000 },
  { provider: "openrouter", id: "openai/gpt-5.5", label: "OpenAI: GPT-5.5", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 1050000 },
  { provider: "openrouter", id: "deepseek/deepseek-v4-pro", label: "DeepSeek: DeepSeek V4 Pro", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high", "max"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "deepseek/deepseek-v4-flash", label: "DeepSeek: DeepSeek V4 Flash", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high", "max"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "inclusionai/ling-2.6-1t", label: "inclusionAI: Ling-2.6-1T", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "tencent/hy3-preview", label: "Tencent: Hy3 preview", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["minimal", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "xiaomi/mimo-v2.5-pro", label: "Xiaomi: MiMo-V2.5-Pro", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "xiaomi/mimo-v2.5", label: "Xiaomi: MiMo-V2.5", tools: true, input: ["text", "image", "audio", "video"], output: ["text"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "inclusionai/ling-2.6-flash", label: "inclusionAI: Ling-2.6-flash", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "~anthropic/claude-opus-latest", label: "Anthropic: Claude Opus Latest", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "moonshotai/kimi-k2.6", label: "MoonshotAI: Kimi K2.6", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 262142 },
  { provider: "openrouter", id: "anthropic/claude-opus-4.7", label: "Anthropic: Claude Opus 4.7", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "z-ai/glm-5.1", label: "Z.ai: GLM 5.1", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 202752 },
  { provider: "openrouter", id: "google/gemma-4-26b-a4b-it:free", label: "Google: Gemma 4 26B A4B  (free)", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "google/gemma-4-26b-a4b-it", label: "Google: Gemma 4 26B A4B ", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "google/gemma-4-31b-it:free", label: "Google: Gemma 4 31B (free)", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "google/gemma-4-31b-it", label: "Google: Gemma 4 31B", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "qwen/qwen3.6-plus", label: "Qwen: Qwen3.6 Plus", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "z-ai/glm-5v-turbo", label: "Z.ai: GLM 5V Turbo", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 202752 },
  { provider: "openrouter", id: "arcee-ai/trinity-large-thinking", label: "Arcee AI: Trinity Large Thinking", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "x-ai/grok-4.20", label: "xAI: Grok 4.20", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 2000000 },
  { provider: "openrouter", id: "kwaipilot/kat-coder-pro-v2", label: "Kwaipilot: KAT-Coder-Pro V2", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 256000 },
  { provider: "openrouter", id: "rekaai/reka-edge", label: "Reka Edge", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingFormat: "openrouter", context: 16384 },
  { provider: "openrouter", id: "minimax/minimax-m2.7", label: "MiniMax: MiniMax M2.7", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 196608 },
  { provider: "openrouter", id: "openai/gpt-5.4-nano", label: "OpenAI: GPT-5.4 Nano", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 400000 },
  { provider: "openrouter", id: "openai/gpt-5.4-mini", label: "OpenAI: GPT-5.4 Mini", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 400000 },
  { provider: "openrouter", id: "mistralai/mistral-small-2603", label: "Mistral: Mistral Small 4", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "z-ai/glm-5-turbo", label: "Z.ai: GLM 5 Turbo", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "nvidia/nemotron-3-super-120b-a12b:free", label: "NVIDIA: Nemotron 3 Super (free)", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "medium", "high"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "nvidia/nemotron-3-super-120b-a12b", label: "NVIDIA: Nemotron 3 Super", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "medium", "high"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "bytedance-seed/seed-2.0-lite", label: "ByteDance Seed: Seed-2.0-Lite", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["minimal", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "qwen/qwen3.5-9b", label: "Qwen: Qwen3.5-9B", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "openai/gpt-5.4-pro", label: "OpenAI: GPT-5.4 Pro", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 1050000 },
  { provider: "openrouter", id: "openai/gpt-5.4", label: "OpenAI: GPT-5.4", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 1050000 },
  { provider: "openrouter", id: "inception/mercury-2", label: "Inception: Mercury 2", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["minimal", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "google/gemini-3.1-flash-lite-preview", label: "Google: Gemini 3.1 Flash Lite Preview", tools: true, input: ["text", "image", "audio", "video"], output: ["text"], thinkingLevels: ["minimal", "low", "medium", "high"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "bytedance-seed/seed-2.0-mini", label: "ByteDance Seed: Seed-2.0-Mini", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["minimal", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "qwen/qwen3.5-35b-a3b", label: "Qwen: Qwen3.5-35B-A3B", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "qwen/qwen3.5-27b", label: "Qwen: Qwen3.5-27B", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "qwen/qwen3.5-122b-a10b", label: "Qwen: Qwen3.5-122B-A10B", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "qwen/qwen3.5-flash-02-23", label: "Qwen: Qwen3.5-Flash", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "google/gemini-3.1-pro-preview-customtools", label: "Google: Gemini 3.1 Pro Preview Custom Tools", tools: true, input: ["text", "image", "audio", "video"], output: ["text"], thinkingLevels: ["low", "medium", "high"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "openai/gpt-5.3-codex", label: "OpenAI: GPT-5.3-Codex", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 400000 },
  { provider: "openrouter", id: "aion-labs/aion-2.0", label: "AionLabs: Aion-2.0", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "google/gemini-3.1-pro-preview", label: "Google: Gemini 3.1 Pro Preview", tools: true, input: ["text", "image", "audio", "video"], output: ["text"], thinkingLevels: ["low", "medium", "high"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "anthropic/claude-sonnet-4.6", label: "Anthropic: Claude Sonnet 4.6", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "max"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "qwen/qwen3.5-plus-02-15", label: "Qwen: Qwen3.5 Plus 2026-02-15", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "qwen/qwen3.5-397b-a17b", label: "Qwen: Qwen3.5 397B A17B", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "minimax/minimax-m2.5", label: "MiniMax: MiniMax M2.5", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["minimal", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 196608 },
  { provider: "openrouter", id: "z-ai/glm-5", label: "Z.ai: GLM 5", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 202752 },
  { provider: "openrouter", id: "qwen/qwen3-max-thinking", label: "Qwen: Qwen3 Max Thinking", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "anthropic/claude-opus-4.6", label: "Anthropic: Claude Opus 4.6", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "max"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "qwen/qwen3-coder-next", label: "Qwen: Qwen3 Coder Next", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "openrouter/free", label: "Free Models Router", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 200000 },
  { provider: "openrouter", id: "stepfun/step-3.5-flash", label: "StepFun: Step 3.5 Flash", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "moonshotai/kimi-k2.5", label: "MoonshotAI: Kimi K2.5", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 256000 },
  { provider: "openrouter", id: "upstage/solar-pro-3", label: "Upstage: Solar Pro 3", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "openai/gpt-audio", label: "OpenAI: GPT Audio", tools: true, input: ["text", "audio"], output: ["text", "audio"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "openai/gpt-audio-mini", label: "OpenAI: GPT Audio Mini", tools: true, input: ["text", "audio"], output: ["text", "audio"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "z-ai/glm-4.7-flash", label: "Z.ai: GLM 4.7 Flash", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 202752 },
  { provider: "openrouter", id: "openai/gpt-5.2-codex", label: "OpenAI: GPT-5.2-Codex", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 400000 },
  { provider: "openrouter", id: "bytedance-seed/seed-1.6-flash", label: "ByteDance Seed: Seed 1.6 Flash", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "bytedance-seed/seed-1.6", label: "ByteDance Seed: Seed 1.6", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "minimax/minimax-m2.1", label: "MiniMax: MiniMax M2.1", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["minimal", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 196608 },
  { provider: "openrouter", id: "z-ai/glm-4.7", label: "Z.ai: GLM 4.7", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high"], thinkingFormat: "openrouter", context: 202752 },
  { provider: "openrouter", id: "google/gemini-3-flash-preview", label: "Google: Gemini 3 Flash Preview", tools: true, input: ["text", "image", "audio", "video"], output: ["text"], thinkingLevels: ["minimal", "low", "medium", "high"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "nvidia/nemotron-3-nano-30b-a3b:free", label: "NVIDIA: Nemotron 3 Nano 30B A3B (free)", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 256000 },
  { provider: "openrouter", id: "nvidia/nemotron-3-nano-30b-a3b", label: "NVIDIA: Nemotron 3 Nano 30B A3B", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "openai/gpt-5.2-chat", label: "OpenAI: GPT-5.2 Chat", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "openai/gpt-5.2-pro", label: "OpenAI: GPT-5.2 Pro", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 400000 },
  { provider: "openrouter", id: "openai/gpt-5.2", label: "OpenAI: GPT-5.2", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 400000 },
  { provider: "openrouter", id: "relace/relace-search", label: "Relace: Relace Search", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 256000 },
  { provider: "openrouter", id: "z-ai/glm-4.6v", label: "Z.ai: GLM 4.6V", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "openai/gpt-5.1-codex-max", label: "OpenAI: GPT-5.1-Codex-Max", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 400000 },
  { provider: "openrouter", id: "amazon/nova-2-lite-v1", label: "Amazon: Nova 2 Lite", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "mistralai/ministral-14b-2512", label: "Mistral: Ministral 3 14B 2512", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "mistralai/ministral-8b-2512", label: "Mistral: Ministral 3 8B 2512", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "mistralai/ministral-3b-2512", label: "Mistral: Ministral 3 3B 2512", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "mistralai/mistral-large-2512", label: "Mistral: Mistral Large 3 2512", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "deepseek/deepseek-v3.2", label: "DeepSeek: DeepSeek V3.2", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "anthropic/claude-opus-4.5", label: "Anthropic: Claude Opus 4.5", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 200000 },
  { provider: "openrouter", id: "openai/gpt-5.1", label: "OpenAI: GPT-5.1", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 400000 },
  { provider: "openrouter", id: "openai/gpt-5.1-codex", label: "OpenAI: GPT-5.1-Codex", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 400000 },
  { provider: "openrouter", id: "openai/gpt-5.1-codex-mini", label: "OpenAI: GPT-5.1-Codex-Mini", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 400000 },
  { provider: "openrouter", id: "moonshotai/kimi-k2-thinking", label: "MoonshotAI: Kimi K2 Thinking", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "amazon/nova-premier-v1", label: "Amazon: Nova Premier 1.0", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "mistralai/voxtral-small-24b-2507", label: "Mistral: Voxtral Small 24B 2507", tools: true, input: ["text", "audio"], output: ["text"], thinkingFormat: "openrouter", context: 32000 },
  { provider: "openrouter", id: "openai/gpt-oss-safeguard-20b", label: "OpenAI: gpt-oss-safeguard-20b", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "nvidia/nemotron-nano-12b-v2-vl:free", label: "NVIDIA: Nemotron Nano 12B 2 VL (free)", tools: true, input: ["text", "image", "video"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "minimax/minimax-m2", label: "MiniMax: MiniMax M2", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 196608 },
  { provider: "openrouter", id: "qwen/qwen3-vl-32b-instruct", label: "Qwen: Qwen3 VL 32B Instruct", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "anthropic/claude-haiku-4.5", label: "Anthropic: Claude Haiku 4.5", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 200000 },
  { provider: "openrouter", id: "qwen/qwen3-vl-8b-thinking", label: "Qwen: Qwen3 VL 8B Thinking", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "qwen/qwen3-vl-8b-instruct", label: "Qwen: Qwen3 VL 8B Instruct", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "qwen/qwen3-vl-30b-a3b-thinking", label: "Qwen: Qwen3 VL 30B A3B Thinking", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "qwen/qwen3-vl-30b-a3b-instruct", label: "Qwen: Qwen3 VL 30B A3B Instruct", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "openai/gpt-5-pro", label: "OpenAI: GPT-5 Pro", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 400000 },
  { provider: "openrouter", id: "z-ai/glm-4.6", label: "Z.ai: GLM 4.6", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 202752 },
  { provider: "openrouter", id: "anthropic/claude-sonnet-4.5", label: "Anthropic: Claude Sonnet 4.5", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "deepseek/deepseek-v3.2-exp", label: "DeepSeek: DeepSeek V3.2 Exp", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 163840 },
  { provider: "openrouter", id: "qwen/qwen3-vl-235b-a22b-thinking", label: "Qwen: Qwen3 VL 235B A22B Thinking", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "qwen/qwen3-vl-235b-a22b-instruct", label: "Qwen: Qwen3 VL 235B A22B Instruct", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "qwen/qwen3-max", label: "Qwen: Qwen3 Max", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "qwen/qwen3-coder-plus", label: "Qwen: Qwen3 Coder Plus", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "deepseek/deepseek-v3.1-terminus", label: "DeepSeek: DeepSeek V3.1 Terminus", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 163840 },
  { provider: "openrouter", id: "qwen/qwen3-coder-flash", label: "Qwen: Qwen3 Coder Flash", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "qwen/qwen3-next-80b-a3b-thinking", label: "Qwen: Qwen3 Next 80B A3B Thinking", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "qwen/qwen3-next-80b-a3b-instruct", label: "Qwen: Qwen3 Next 80B A3B Instruct", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "qwen/qwen-plus-2025-07-28:thinking", label: "Qwen: Qwen Plus 0728 (thinking)", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "qwen/qwen-plus-2025-07-28", label: "Qwen: Qwen Plus 0728", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "nvidia/nemotron-nano-9b-v2:free", label: "NVIDIA: Nemotron Nano 9B V2 (free)", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "moonshotai/kimi-k2-0905", label: "MoonshotAI: Kimi K2 0905", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "qwen/qwen3-30b-a3b-thinking-2507", label: "Qwen: Qwen3 30B A3B Thinking 2507", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "deepseek/deepseek-chat-v3.1", label: "DeepSeek: DeepSeek V3.1", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 163840 },
  { provider: "openrouter", id: "mistralai/mistral-medium-3.1", label: "Mistral: Mistral Medium 3.1", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "z-ai/glm-4.5v", label: "Z.ai: GLM 4.5V", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 65536 },
  { provider: "openrouter", id: "ai21/jamba-large-1.7", label: "AI21: Jamba Large 1.7", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 256000 },
  { provider: "openrouter", id: "openai/gpt-5", label: "OpenAI: GPT-5", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 400000 },
  { provider: "openrouter", id: "openai/gpt-5-mini", label: "OpenAI: GPT-5 Mini", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 400000 },
  { provider: "openrouter", id: "openai/gpt-5-nano", label: "OpenAI: GPT-5 Nano", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 400000 },
  { provider: "openrouter", id: "openai/gpt-oss-120b", label: "OpenAI: gpt-oss-120b", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["low", "medium", "high"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "openai/gpt-oss-20b:free", label: "OpenAI: gpt-oss-20b (free)", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["low", "medium", "high"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "openai/gpt-oss-20b", label: "OpenAI: gpt-oss-20b", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["low", "medium", "high"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "anthropic/claude-opus-4.1", label: "Anthropic: Claude Opus 4.1", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 200000 },
  { provider: "openrouter", id: "mistralai/codestral-2508", label: "Mistral: Codestral 2508", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 256000 },
  { provider: "openrouter", id: "qwen/qwen3-coder-30b-a3b-instruct", label: "Qwen: Qwen3 Coder 30B A3B Instruct", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 160000 },
  { provider: "openrouter", id: "qwen/qwen3-30b-a3b-instruct-2507", label: "Qwen: Qwen3 30B A3B Instruct 2507", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "z-ai/glm-4.5", label: "Z.ai: GLM 4.5", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "z-ai/glm-4.5-air", label: "Z.ai: GLM 4.5 Air", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "qwen/qwen3-235b-a22b-thinking-2507", label: "Qwen: Qwen3 235B A22B Thinking 2507", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "qwen/qwen3-coder", label: "Qwen: Qwen3 Coder 480B A35B", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "google/gemini-2.5-flash-lite", label: "Google: Gemini 2.5 Flash Lite", tools: true, input: ["text", "image", "audio", "video"], output: ["text"], thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "qwen/qwen3-235b-a22b-2507", label: "Qwen: Qwen3 235B A22B Instruct 2507", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 262144 },
  { provider: "openrouter", id: "moonshotai/kimi-k2", label: "MoonshotAI: Kimi K2 0711", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "mistralai/mistral-small-3.2-24b-instruct", label: "Mistral: Mistral Small 3.2 24B", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "minimax/minimax-m1", label: "MiniMax: MiniMax M1", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "google/gemini-2.5-flash", label: "Google: Gemini 2.5 Flash", tools: true, input: ["text", "image", "audio", "video"], output: ["text"], thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "google/gemini-2.5-pro", label: "Google: Gemini 2.5 Pro", tools: true, input: ["text", "image", "audio", "video"], output: ["text"], thinkingLevels: ["minimal", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "openai/o3-pro", label: "OpenAI: o3 Pro", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 200000 },
  { provider: "openrouter", id: "google/gemini-2.5-pro-preview", label: "Google: Gemini 2.5 Pro Preview 06-05", tools: true, input: ["text", "image", "audio"], output: ["text"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "deepseek/deepseek-r1-0528", label: "DeepSeek: R1 0528", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 163840 },
  { provider: "openrouter", id: "anthropic/claude-opus-4", label: "Anthropic: Claude Opus 4", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 200000 },
  { provider: "openrouter", id: "anthropic/claude-sonnet-4", label: "Anthropic: Claude Sonnet 4", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh", "max"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "mistralai/mistral-medium-3", label: "Mistral: Mistral Medium 3", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "google/gemini-2.5-pro-preview-05-06", label: "Google: Gemini 2.5 Pro Preview 05-06", tools: true, input: ["text", "image", "audio", "video"], output: ["text"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "arcee-ai/virtuoso-large", label: "Arcee AI: Virtuoso Large", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "qwen/qwen3-30b-a3b", label: "Qwen: Qwen3 30B A3B", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 40960 },
  { provider: "openrouter", id: "qwen/qwen3-8b", label: "Qwen: Qwen3 8B", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 40960 },
  { provider: "openrouter", id: "qwen/qwen3-14b", label: "Qwen: Qwen3 14B", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 40960 },
  { provider: "openrouter", id: "qwen/qwen3-32b", label: "Qwen: Qwen3 32B", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 40960 },
  { provider: "openrouter", id: "qwen/qwen3-235b-a22b", label: "Qwen: Qwen3 235B A22B", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "high"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "openai/o4-mini-high", label: "OpenAI: o4 Mini High", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["low", "medium", "high"], thinkingFormat: "openrouter", context: 200000 },
  { provider: "openrouter", id: "openai/o3", label: "OpenAI: o3", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 200000 },
  { provider: "openrouter", id: "openai/o4-mini", label: "OpenAI: o4 Mini", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 200000 },
  { provider: "openrouter", id: "openai/gpt-4.1", label: "OpenAI: GPT-4.1", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 1047576 },
  { provider: "openrouter", id: "openai/gpt-4.1-mini", label: "OpenAI: GPT-4.1 Mini", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 1047576 },
  { provider: "openrouter", id: "openai/gpt-4.1-nano", label: "OpenAI: GPT-4.1 Nano", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 1047576 },
  { provider: "openrouter", id: "meta-llama/llama-4-maverick", label: "Meta: Llama 4 Maverick", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 1048576 },
  { provider: "openrouter", id: "meta-llama/llama-4-scout", label: "Meta: Llama 4 Scout", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 327680 },
  { provider: "openrouter", id: "deepseek/deepseek-chat-v3-0324", label: "DeepSeek: DeepSeek V3 0324", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 163840 },
  { provider: "openrouter", id: "google/gemma-3-12b-it", label: "Google: Gemma 3 12B", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "google/gemma-3-27b-it", label: "Google: Gemma 3 27B", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "mistralai/mistral-saba", label: "Mistral: Saba", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 32768 },
  { provider: "openrouter", id: "openai/o3-mini-high", label: "OpenAI: o3 Mini High", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["low", "medium", "high"], thinkingFormat: "openrouter", context: 200000 },
  { provider: "openrouter", id: "qwen/qwen-plus", label: "Qwen: Qwen-Plus", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 1000000 },
  { provider: "openrouter", id: "openai/o3-mini", label: "OpenAI: o3 Mini", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 200000 },
  { provider: "openrouter", id: "deepseek/deepseek-r1", label: "DeepSeek: R1", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 64000 },
  { provider: "openrouter", id: "deepseek/deepseek-chat", label: "DeepSeek: DeepSeek V3", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "openai/o1", label: "OpenAI: o1", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 200000 },
  { provider: "openrouter", id: "meta-llama/llama-3.3-70b-instruct", label: "Meta: Llama 3.3 70B Instruct", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "amazon/nova-lite-v1", label: "Amazon: Nova Lite 1.0", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 300000 },
  { provider: "openrouter", id: "amazon/nova-micro-v1", label: "Amazon: Nova Micro 1.0", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "amazon/nova-pro-v1", label: "Amazon: Nova Pro 1.0", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 300000 },
  { provider: "openrouter", id: "openai/gpt-4o-2024-11-20", label: "OpenAI: GPT-4o (2024-11-20)", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "mistralai/mistral-large-2407", label: "Mistral Large 2407", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "thedrummer/unslopnemo-12b", label: "TheDrummer: UnslopNemo 12B", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 32768 },
  { provider: "openrouter", id: "qwen/qwen-2.5-7b-instruct", label: "Qwen: Qwen2.5 7B Instruct", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 32768 },
  { provider: "openrouter", id: "qwen/qwen-2.5-72b-instruct", label: "Qwen2.5 72B Instruct", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 32768 },
  { provider: "openrouter", id: "cohere/command-r-08-2024", label: "Cohere: Command R (08-2024)", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "cohere/command-r-plus-08-2024", label: "Cohere: Command R+ (08-2024)", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "sao10k/l3.1-euryale-70b", label: "Sao10K: Llama 3.1 Euryale 70B v2.2", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "openai/gpt-4o-2024-08-06", label: "OpenAI: GPT-4o (2024-08-06)", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "meta-llama/llama-3.1-70b-instruct", label: "Meta: Llama 3.1 70B Instruct", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "meta-llama/llama-3.1-8b-instruct", label: "Meta: Llama 3.1 8B Instruct", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "mistralai/mistral-nemo", label: "Mistral: Mistral Nemo", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 131072 },
  { provider: "openrouter", id: "openai/gpt-4o-mini-2024-07-18", label: "OpenAI: GPT-4o-mini (2024-07-18)", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "openai/gpt-4o-mini", label: "OpenAI: GPT-4o-mini", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "openai/gpt-4o", label: "OpenAI: GPT-4o", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "openai/gpt-4o-2024-05-13", label: "OpenAI: GPT-4o (2024-05-13)", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "mistralai/mixtral-8x22b-instruct", label: "Mistral: Mixtral 8x22B Instruct", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 65536 },
  { provider: "openrouter", id: "openai/gpt-4-turbo", label: "OpenAI: GPT-4 Turbo", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "anthropic/claude-3-haiku", label: "Anthropic: Claude 3 Haiku", tools: true, input: ["text", "image"], output: ["text"], thinkingFormat: "openrouter", context: 200000 },
  { provider: "openrouter", id: "mistralai/mistral-large", label: "Mistral Large", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "openai/gpt-3.5-turbo-0613", label: "OpenAI: GPT-3.5 Turbo (older v0613)", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 4095 },
  { provider: "openrouter", id: "openai/gpt-4-turbo-preview", label: "OpenAI: GPT-4 Turbo Preview", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 128000 },
  { provider: "openrouter", id: "openrouter/auto", label: "Auto Router", tools: true, input: ["text", "image", "audio", "video"], output: ["text", "image"], thinkingFormat: "openrouter", context: 2000000 },
  { provider: "openrouter", id: "openai/gpt-3.5-turbo-16k", label: "OpenAI: GPT-3.5 Turbo 16k", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 16385 },
  { provider: "openrouter", id: "openai/gpt-3.5-turbo", label: "OpenAI: GPT-3.5 Turbo", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 16385 },
  { provider: "openrouter", id: "openai/gpt-4", label: "OpenAI: GPT-4", tools: true, input: ["text"], output: ["text"], thinkingFormat: "openrouter", context: 8191 },

  // ---- together (3) ------------------------------------------------
  { provider: "together", id: "deepseek-ai/DeepSeek-V4-Pro", label: "DeepSeek V4 Pro", tools: true, input: ["text"], output: ["text"], context: 512000 },
  { provider: "together", id: "moonshotai/Kimi-K2.5", label: "Kimi K2.5", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "together", id: "meta-llama/Llama-3.3-70B-Instruct-Turbo", label: "Llama 3.3 70B", tools: true, input: ["text"], output: ["text"], context: 131072 },

  // ---- groq (6) ----------------------------------------------------
  { provider: "groq", id: "openai/gpt-oss-120b", label: "GPT-OSS 120B", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["low", "medium", "high"], context: 131072 },
  { provider: "groq", id: "openai/gpt-oss-20b", label: "GPT-OSS 20B", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["low", "medium", "high"], context: 131072 },
  { provider: "groq", id: "qwen/qwen3-32b", label: "Qwen3 32B", tools: true, input: ["text"], output: ["text"], context: 131072 },
  { provider: "groq", id: "llama-3.3-70b-versatile", label: "Llama 3.3 70B", tools: true, input: ["text"], output: ["text"], context: 131072 },
  { provider: "groq", id: "llama-3.1-8b-instant", label: "Llama 3.1 8B Instant", tools: true, input: ["text"], output: ["text"], context: 131072 },
  { provider: "groq", id: "meta-llama/llama-4-scout-17b-16e-instruct", label: "Llama 4 Scout 17Bx16E", tools: true, input: ["text", "image"], output: ["text"], context: 131072 },

  // ---- ollama (45) --------------------------------------------------
  { provider: "ollama", id: "cogito-2.1:671b-cloud", label: "Cogito 2.1 671B Cloud", tools: true, input: ["text"], output: ["text"], context: 163840 },
  { provider: "ollama", id: "deepseek-v3.1:671b-cloud", label: "DeepSeek V3.1 671B Cloud", tools: true, input: ["text"], output: ["text"], context: 163840 },
  { provider: "ollama", id: "deepseek-v3.2:cloud", label: "DeepSeek V3.2 Cloud", tools: true, input: ["text"], output: ["text"], context: 163840 },
  { provider: "ollama", id: "deepseek-v4-flash:cloud", label: "DeepSeek V4 Flash Cloud", tools: true, input: ["text"], output: ["text"], context: 1048576 },
  { provider: "ollama", id: "deepseek-v4-pro:cloud", label: "DeepSeek V4 Pro Cloud", tools: true, input: ["text"], output: ["text"], context: 1048576 },
  { provider: "ollama", id: "devstral-2:123b-cloud", label: "Devstral 2 123B Cloud", tools: true, input: ["text"], output: ["text"], context: 262144 },
  { provider: "ollama", id: "devstral-small-2:24b-cloud", label: "Devstral Small 2 24B Cloud", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "ollama", id: "gemini-3-flash-preview:cloud", label: "Gemini 3 Flash Preview Cloud", tools: true, input: ["text", "image"], output: ["text"], context: 1048576 },
  { provider: "ollama", id: "gemma3:12b-cloud", label: "Gemma 3 12B Cloud", tools: true, input: ["text", "image"], output: ["text"], context: 131072 },
  { provider: "ollama", id: "gemma3:27b-cloud", label: "Gemma 3 27B Cloud", tools: true, input: ["text", "image"], output: ["text"], context: 131072 },
  { provider: "ollama", id: "gemma3:4b-cloud", label: "Gemma 3 4B Cloud", tools: true, input: ["text", "image"], output: ["text"], context: 131072 },
  { provider: "ollama", id: "gemma4:31b-cloud", label: "Gemma 4 31B Cloud", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "ollama", id: "glm-4.6:cloud", label: "GLM 4.6 Cloud", tools: true, input: ["text"], output: ["text"], context: 202752 },
  { provider: "ollama", id: "glm-4.7:cloud", label: "GLM 4.7 Cloud", tools: true, input: ["text"], output: ["text"], context: 202752 },
  { provider: "ollama", id: "glm-5:cloud", label: "GLM 5 Cloud", tools: true, input: ["text"], output: ["text"], context: 202752 },
  { provider: "ollama", id: "glm-5.1:cloud", label: "GLM 5.1 Cloud", tools: true, input: ["text"], output: ["text"], context: 202752 },
  { provider: "ollama", id: "glm-5.2:cloud", label: "GLM 5.2 Cloud", tools: true, input: ["text"], output: ["text"], context: 976000 },
  { provider: "ollama", id: "gpt-oss:120b-cloud", label: "GPT-OSS 120B Cloud", tools: true, input: ["text"], output: ["text"], context: 131072 },
  { provider: "ollama", id: "gpt-oss:20b-cloud", label: "GPT-OSS 20B Cloud", tools: true, input: ["text"], output: ["text"], context: 131072 },
  { provider: "ollama", id: "kimi-k2-thinking:cloud", label: "Kimi K2 Thinking Cloud", tools: true, input: ["text"], output: ["text"], context: 262144 },
  { provider: "ollama", id: "kimi-k2.5:cloud", label: "Kimi K2.5 Cloud", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "ollama", id: "kimi-k2.6:cloud", label: "Kimi K2.6 Cloud", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "ollama", id: "kimi-k2.7-code:cloud", label: "Kimi K2.7 Code Cloud", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "ollama", id: "kimi-k2:1t-cloud", label: "Kimi K2 1T Cloud", tools: true, input: ["text"], output: ["text"], context: 262144 },
  { provider: "ollama", id: "kimi-k3:cloud", label: "Kimi K3 Cloud", tools: true, input: ["text", "image"], output: ["text"], context: 1048576 },
  { provider: "ollama", id: "minimax-m2:cloud", label: "MiniMax M2 Cloud", tools: true, input: ["text"], output: ["text"], context: 204800 },
  { provider: "ollama", id: "minimax-m2.1:cloud", label: "MiniMax M2.1 Cloud", tools: true, input: ["text"], output: ["text"], context: 204800 },
  { provider: "ollama", id: "minimax-m2.5:cloud", label: "MiniMax M2.5 Cloud", tools: true, input: ["text"], output: ["text"], context: 202752 },
  { provider: "ollama", id: "minimax-m2.7:cloud", label: "MiniMax M2.7 Cloud", tools: true, input: ["text"], output: ["text"], context: 204800 },
  { provider: "ollama", id: "minimax-m3:cloud", label: "MiniMax M3 Cloud", tools: true, input: ["text", "image"], output: ["text"], context: 512000 },
  { provider: "ollama", id: "ministral-3:14b-cloud", label: "Ministral 3 14B Cloud", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "ollama", id: "ministral-3:3b-cloud", label: "Ministral 3 3B Cloud", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "ollama", id: "ministral-3:8b-cloud", label: "Ministral 3 8B Cloud", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "ollama", id: "mistral-large-3:675b-cloud", label: "Mistral Large 3 675B Cloud", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "ollama", id: "nemotron-3-nano:30b-cloud", label: "Nemotron 3 Nano 30B Cloud", tools: true, input: ["text"], output: ["text"], context: 1048576 },
  { provider: "ollama", id: "nemotron-3-super:cloud", label: "Nemotron 3 Super Cloud", tools: true, input: ["text"], output: ["text"], context: 262144 },
  { provider: "ollama", id: "nemotron-3-ultra:cloud", label: "Nemotron 3 Ultra Cloud", tools: true, input: ["text"], output: ["text"], context: 262144 },
  { provider: "ollama", id: "qwen3-coder-next:cloud", label: "Qwen3 Coder Next Cloud", tools: true, input: ["text"], output: ["text"], context: 262144 },
  { provider: "ollama", id: "qwen3-coder:480b-cloud", label: "Qwen3 Coder 480B Cloud", tools: true, input: ["text"], output: ["text"], context: 262144 },
  { provider: "ollama", id: "qwen3-next:80b-cloud", label: "Qwen3 Next 80B Cloud", tools: true, input: ["text"], output: ["text"], context: 262144 },
  { provider: "ollama", id: "qwen3-vl:235b-cloud", label: "Qwen3 VL 235B Cloud", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "ollama", id: "qwen3-vl:235b-instruct-cloud", label: "Qwen3 VL 235B Instruct Cloud", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "ollama", id: "qwen3.5:cloud", label: "Qwen3.5 Cloud", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "ollama", id: "qwen3.5:397b-cloud", label: "Qwen3.5 397B Cloud", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "ollama", id: "rnj-1:8b-cloud", label: "RNJ 1 8B Cloud", tools: true, input: ["text"], output: ["text"], context: 32768 },

  // ---- cerebras (3) ------------------------------------------------
  { provider: "cerebras", id: "gpt-oss-120b", label: "GPT OSS 120B", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["low", "medium", "high"], context: 131072 },
  { provider: "cerebras", id: "zai-glm-4.7", label: "Z.ai GLM 4.7", tools: true, input: ["text"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high"], context: 131072 },
  { provider: "cerebras", id: "gemma-4-31b", label: "Gemma 4 31B", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "low", "medium", "high"], context: 131072 },

  // ---- mistral (35) --------------------------------------------------
  { provider: "mistral", id: "codestral-2508", label: "codestral-2508", tools: true, input: ["text"], output: ["text"], context: 256000 },
  { provider: "mistral", id: "codestral-latest", label: "codestral-latest", tools: true, input: ["text"], output: ["text"], context: 256000 },
  { provider: "mistral", id: "devstral-2512", label: "devstral-2512", tools: true, input: ["text"], output: ["text"], context: 262144 },
  { provider: "mistral", id: "devstral-latest", label: "devstral-latest", tools: true, input: ["text"], output: ["text"], context: 262144 },
  { provider: "mistral", id: "devstral-medium-latest", label: "devstral-medium-latest", tools: true, input: ["text"], output: ["text"], context: 262144 },
  { provider: "mistral", id: "labs-leanstral-1-5", label: "labs-leanstral-1-5", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "high"], context: 262144 },
  { provider: "mistral", id: "labs-leanstral-1-5-1", label: "labs-leanstral-1-5-1", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "mistral", id: "magistral-medium-latest", label: "magistral-medium-latest", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "high"], context: 262144 },
  { provider: "mistral", id: "magistral-small-latest", label: "magistral-small-latest", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "high"], context: 262144 },
  { provider: "mistral", id: "ministral-14b-2512", label: "ministral-14b-2512", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "mistral", id: "ministral-14b-latest", label: "ministral-14b-latest", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "mistral", id: "ministral-3b-2512", label: "ministral-3b-2512", tools: true, input: ["text", "image"], output: ["text"], context: 131072 },
  { provider: "mistral", id: "ministral-3b-latest", label: "ministral-3b-latest", tools: true, input: ["text", "image"], output: ["text"], context: 131072 },
  { provider: "mistral", id: "ministral-8b-2512", label: "ministral-8b-2512", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "mistral", id: "ministral-8b-latest", label: "ministral-8b-latest", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "mistral", id: "mistral-code-agent-latest", label: "mistral-code-agent-latest", tools: true, input: ["text"], output: ["text"], context: 262144 },
  { provider: "mistral", id: "mistral-code-fim-latest", label: "mistral-code-fim-latest", tools: true, input: ["text"], output: ["text"], context: 256000 },
  { provider: "mistral", id: "mistral-code-latest", label: "mistral-code-latest", tools: true, input: ["text"], output: ["text"], context: 256000 },
  { provider: "mistral", id: "mistral-large-2512", label: "mistral-large-2512", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "mistral", id: "mistral-large-latest", label: "mistral-large-latest", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "mistral", id: "mistral-medium", label: "mistral-medium", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "mistral", id: "mistral-medium-2505", label: "mistral-medium-2505", tools: true, input: ["text", "image"], output: ["text"], context: 131072 },
  { provider: "mistral", id: "mistral-medium-2508", label: "mistral-medium-2508", tools: true, input: ["text", "image"], output: ["text"], context: 131072 },
  { provider: "mistral", id: "mistral-medium-2604", label: "mistral-medium-2604", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "mistral", id: "mistral-medium-3", label: "mistral-medium-3", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "mistral", id: "mistral-medium-3-5", label: "mistral-medium-3-5", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "mistral", id: "mistral-medium-3.5", label: "mistral-medium-3.5", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "mistral", id: "mistral-medium-latest", label: "mistral-medium-latest", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "high"], context: 262144 },
  { provider: "mistral", id: "mistral-small-2603", label: "mistral-small-2603", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "mistral", id: "mistral-small-latest", label: "mistral-small-latest", tools: true, input: ["text", "image"], output: ["text"], thinkingLevels: ["off", "high"], context: 262144 },
  { provider: "mistral", id: "mistral-vibe-cli-fast", label: "mistral-vibe-cli-fast", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "mistral", id: "mistral-vibe-cli-latest", label: "mistral-vibe-cli-latest", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "mistral", id: "mistral-vibe-cli-with-tools", label: "mistral-vibe-cli-with-tools", tools: true, input: ["text", "image"], output: ["text"], context: 262144 },
  { provider: "mistral", id: "voxtral-small-2507", label: "voxtral-small-2507", tools: true, input: ["text"], output: ["text"], context: 32768 },
  { provider: "mistral", id: "voxtral-small-latest", label: "voxtral-small-latest", tools: true, input: ["text"], output: ["text"], context: 32768 },

]
